spring:
  application:
    name: user
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/userDb?authSource=admin
      database: userDb
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web : debug