spring:
  application:
    name: user
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/userDb?authSource=admin
      database: userDb
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    org:
      springframework:
        web : debug